// resources/js/dashboard.js
import './calendarSelects.js';
import './elemento1dashboard.js';
import './dashboardHeatmap.js';
import './linetime.js';
import './efectividad.js';
import './tops.js';
import './creatComplet.js';
import './minmachdesc.js';
